# Generated by Django 4.2.7 on 2025-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
